protected/models/Country.php
<?php

/**
 * This is the model class for table "tbl_country".
 */
class Country extends CActiveRecord
{
	/**
	 * The followings are the available columns in table 'tbl_country':
	 * @property integer $id
	 * @property string $code
	 * @property string $name
	 * @property integer $call_code
	 */

	/**
	 * Returns the static model of the specified AR class.
	 * @return Country the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_country';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('name', 'required'),
			array('call_code', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>2),
			array('name', 'length', 'max'=>100),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'persons' => array(self::HAS_MANY, 'Person', 'country_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('ui', 'ID'),
			'code' => Yii::t('ui', 'Code'),
			'name' => Yii::t('ui', 'Name'),
			'call_code' => Yii::t('ui', 'Call Code'),
		);
	}

	/**
	 * Suggests a list of existing values matching the specified keyword.
	 * @param string the keyword to be matched
	 * @param integer maximum number of names to be returned
	 * @return array list of matching lastnames
	 */
	public function suggest($keyword,$limit=20)
	{
		$models=$this->findAll(array(
			'condition'=>'name LIKE :keyword',
			'order'=>'name',
			'limit'=>$limit,
			'params'=>array(':keyword'=>"%$keyword%")
		));
		$suggest=array();
		foreach($models as $model) {
			$suggest[] = array(
				'label'=>$model->name.' - '.$model->code.' - '.$model->call_code,  // label for dropdown list
				'value'=>$model->name,  // value for input field
				'id'=>$model->id,       // return values from autocomplete
				'code'=>$model->code,
				'call_code'=>$model->call_code,
			);
		}
		return $suggest;
	}

	/**
	 * Suggests a list of existing fullnames matching the specified keyword.
	 * @param string the keyword to be matched
	 * @param integer maximum number of names to be returned
	 * @return array list of matching fullnames
	 */
	public function legacySuggest($keyword,$limit=20)
	{
		$models=$this->findAll(array(
			'condition'=>'name LIKE :keyword',
			'order'=>'name',
			'limit'=>$limit,
			'params'=>array(':keyword'=>"%$keyword%")
		));
		$suggest=array();
		foreach($models as $model)
			$suggest[]=$model->name.' - '.$model->code.' - '.$model->call_code.'|'.$model->name.'|'.$model->code.'|'.$model->call_code;
		return $suggest;
	}

	/**
	 * @return array for dropdown (attr1 => attr2)
	 */
	public function getOptions()
	{
		return CHtml::listData($this->findAll(),'id','name');
	}
}

protected/models/Person.php
<?php

/**
 * This is the model class for table "tbl_person".
 */
class Person extends CActiveRecord
{
	/**
	 * The followings are the available columns in table 'tbl_person':
	 * @property integer $id
	 * @property string $firstname
	 * @property string $lastname
	 * @property integer $birthyear
	 * @property string $email
	 * @property string $webpage
	 * @property integer $country_id
	 * @property string $registered
	 * @property integer $eyecolor_code
	 */

	/**
	 * Returns the static model of the specified AR class.
	 * @return Person the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tbl_person';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('firstname, lastname, country_id', 'required'),
			array('birthyear, country_id, eyecolor_code', 'numerical', 'integerOnly'=>true),
			array('firstname, lastname, email, webpage', 'length', 'max'=>64),
			array('registered', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, firstname, lastname, birthyear, email, webpage, country_id, registered, eyecolor_code', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('ui', 'ID'),
			'firstname' => Yii::t('ui', 'Firstname'),
			'lastname' => Yii::t('ui', 'Lastname'),
			'birthyear' => Yii::t('ui', 'Birth'),
			'email' => Yii::t('ui', 'Email'),
			'webpage' => Yii::t('ui', 'Webpage'),
			'country_id' => Yii::t('ui', 'Country'),
			'registered' => Yii::t('ui', 'Registered'),
			'eyecolor_code' => Yii::t('ui', 'Eyecolor'),
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new XDbCriteria(array(
			'with'=>'country',
		));

		$criteria->compare('id',$this->id);
		$criteria->icompare('firstname',$this->firstname,true);
		$criteria->icompare('lastname',$this->lastname,true);
		$criteria->compare('birthyear',$this->birthyear);
		$criteria->icompare('email',$this->email,true);
		$criteria->icompare('webpage',$this->webpage,true);
		$criteria->compare('country_id',$this->country_id);
		$criteria->icompare('registered',$this->registered,true);
		$criteria->compare('eyecolor_code',$this->eyecolor_code);

		return new CActiveDataProvider(get_class($this), array(
			'criteria'=>$criteria,
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['pageSize'],
				'pageVar'=>'page',
			),
			'sort'=>array(
				'defaultOrder'=>'lastname,firstname',
				'sortVar'=>'sort',
				'attributes'=>array(
					'firstname',
					'lastname',
					'birthyear',
					'country_id'=>array(
						'asc'=>'country.name',
						'desc'=>'country.name DESC',
					)
				),
			),

		));
	}

	/**
	 * @return string reference code of given map
	 */
	public function getFullname()
	{
		return $this->firstname.' '.$this->lastname;
	}

	/**
	 * @param string attribute name
	 * @return array for XAlphaPagination (A,B,C,etc)
	 */
	public function getAlphaChars($attribute)
	{
		$chars=array();
		$criteria=array(
			'select'=>"DISTINCT(SUBSTR(\"$attribute\",1,1)) AS \"$attribute\"",
			'order'=>"$attribute",
		);
		$models=$this->findAll($criteria);
		foreach($models as $model)
			$chars[]=mb_strtoupper($model->$attribute);
		return $chars;
	}

	/**
	 * @param int $country_id
	 * @return array for listbuilder (id => name)
	 */
	public function findUsersByCountry($country_id)
	{
		$criteria=array(
			'select'=>"id, firstname || ' ' || lastname AS firstname",
			'condition'=>'country_id='.$country_id,
			'order'=>'firstname, lastname',
		);
		return CHtml::listData($this->findAll($criteria),'id','firstname');
	}

	/**
	 * @param int $id the id (primary key) of person
	 * @param int $country_id
	 */
	public function updateUserCountry($id, $country_id)
	{
		$model=$this->findByPk($id);
		$model->country_id=$country_id;
		$model->update('country_id');
	}

	/**
	 * This is invoked when a record is populated with data from a find() call.
	 */
	protected function afterFind()
	{
		parent::afterFind();
		$this->registered=date("d.m.Y", strtotime($this->registered));
	}
}

protected/controllers/PersonController.php
<?php

class PersonController extends Controller
{
	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @var string the default layout for the views.
	 */
	public $layout='leftbar';

	/**
	 * initialize the default portlets for the views
	 */
	function init()
	{
		parent::init();
		$this->leftPortlets['ptl.WidgetMenu']=array();
	}


	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','admin','view','alpha','batch','updateYears'),
				'users'=>array('*'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('create','update','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$this->render('view',array(
			'model'=>$this->loadModel(),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Person;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Person']))
		{
			$model->attributes=$_POST['Person'];
			if($model->save())
			{
				if(!$this->goBack())
					$this->redirect(array('admin'));
				else
					$this->goBack();
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Person']))
		{
			$model->attributes=$_POST['Person'];
			if($model->save())
			{
				if(!$this->goBack())
					$this->redirect(array('admin'));
				else
					$this->goBack();
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Person', array(
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['pageSize'],
				'pageVar'=>'page',
			),
			'sort'=>array(
				'defaultOrder'=>'lastname',
			),
		));
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Person('search');
		if(isset($_GET['Person']))
			$model->attributes=$_GET['Person'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models with batch menu.
	 */
	public function actionBatch()
	{
		$model=new Person('search');
		if(isset($_GET['Person']))
			$model->attributes=$_GET['Person'];

		$this->render('batch',array(
			'model'=>$model,
		));
	}

	/**
	 * Manages all models with batch menu.
	 */
	public function actionCmenu()
	{
		$model=new Person('search');
		if(isset($_GET['Person']))
			$model->attributes=$_GET['Person'];

		$this->render('cmenu',array(
			'model'=>$model,
		));
	}

	/**
	 * Lists all models.
	 */
	public function actionAlpha()
	{
		// AlphaPagination
		Yii::import('ext.widgets.alphapager.XAlphaPagination');
		$criteria=new CDbCriteria;
		$alphaPages = new XAlphaPagination('lastname');
		$alphaPages->charSet = Person::model()->getAlphaChars('lastname');
		$alphaPages->applyCondition($criteria);

		// Dataprovider
		$dataProvider=new CActiveDataProvider('Person', array(
			'criteria'=>$criteria,
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['pageSize'],
				'pageVar'=>'page',
			),
			'sort'=>array(
				'defaultOrder'=>'lastname',
			),
		));
		$this->render('alpha',array(
			'dataProvider'=>$dataProvider,
			'alphaPages'=>$alphaPages,
		));
	}

	/**
	 * Make selected persons 10 years older.
	 */
	public function actionUpdateYears()
	{
		// we only allow POST request
		if(Yii::app()->request->isPostRequest)
		{
			$increment=!empty($_GET['op']) && $_GET['op']=='more' ?  1 : -1;
			$criteria=new CDbCriteria();
			$criteria->addInCondition('id', $_POST['person-id']);
			Person::model()->updateCounters(array('birthyear'=>$increment), $criteria);

			// if AJAX request, we should not redirect the browser
			if(!isset($_GET['ajax']))
			{
				if(!$this->goBack())
					$this->redirect(array('batch'));
				else
					$this->goBack();
			}
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=Person::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='person-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/person/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'person-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p><?php echo Yii::t('ui', 'Fields with {mark} are required',
	array('{mark}'=>'<span class="required">*</span>')); ?>
</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="simple">
		<?php echo $form->labelEx($model,'firstname'); ?>
		<?php echo $form->textField($model,'firstname',array('size'=>40,'maxlength'=>64)); ?>
		<?php echo $form->error($model,'firstname'); ?>
	</div>

	<div class="simple">
		<?php echo $form->labelEx($model,'lastname'); ?>
		<?php echo $form->textField($model,'lastname',array('size'=>40,'maxlength'=>64)); ?>
		<?php echo $form->error($model,'lastname'); ?>
	</div>

	<div class="simple">
		<?php echo $form->labelEx($model,'birthyear'); ?>
		<?php echo $form->textField($model,'birthyear',array('size'=>6,'maxlength'=>4)); ?>
		<?php echo $form->error($model,'birthyear'); ?>
	</div>

	<div class="simple">
		<?php echo $form->labelEx($model,'email'); ?>
		<?php echo $form->textField($model,'email',array('size'=>40,'maxlength'=>64)); ?>
		<?php echo $form->error($model,'email'); ?>
	</div>

	<div class="simple">
		<?php echo $form->labelEx($model,'webpage'); ?>
		<?php echo $form->textField($model,'webpage',array('size'=>40,'maxlength'=>64)); ?>
		<?php echo $form->error($model,'webpage'); ?>
	</div>

	<div class="simple">
		<?php echo $form->labelEx($model,'country_id'); ?>
		<?php echo $form->DropDownList($model,'country_id',Country::model()->options,array('prompt'=>''));?>
		<?php echo $form->error($model,'country_id'); ?>
	</div>

	<div class="simple">
		<?php echo $form->labelEx($model,'eyecolor_code'); ?>
		<?php echo $form->dropDownList($model,'eyecolor_code',Lookup::items('eyecolor'),array('prompt'=>''));?>
		<?php echo $form->error($model,'eyecolor_code'); ?>
	</div>

	<div class="action">
		<?php echo CHtml::submitButton($model->isNewRecord ? Yii::t('ui', 'Create') : Yii::t('ui','Save')); ?>
		<?php echo CHtml::button(Yii::t('ui', 'Cancel'), array('submit' => $model->isNewRecord ? array('admin') : $this->getReturnUrl())) ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/person/_view.php
<div class="item">

	<h3><?php echo CHtml::link($data->fullname,$this->createReturnableUrl('view',array('id'=>$data->id)));?></h3>

	<b><?php echo CHtml::encode($data->getAttributeLabel('birthyear')); ?>:</b>
	<?php echo CHtml::encode($data->birthyear); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('email')); ?>:</b>
	<?php echo CFormatter::formatEmail($data->email); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('webpage')); ?>:</b>
	<?php echo CFormatter::formatUrl($data->webpage); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('country_id')); ?>:</b>
	<?php echo CHtml::encode($data->country->name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('eyecolor_code')); ?>:</b>
	<?php echo Lookup::item('eyecolor',$data->eyecolor_code); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('registered')); ?>:</b>
	<?php echo CHtml::encode($data->registered); ?>
	<br />

</div>

protected/views/person/admin.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Yii::t('ui', 'Manage Persons');

$this->breadcrumbs=array(
	Yii::t('ui','Persons'),
);
?>

<h2><?php echo Yii::t('ui', 'Manage Persons'); ?></h2>

<div class="actionBar">
<?php echo CHtml::link(Yii::t('ui', 'New'),array('create')); ?>
</div> <!-- actionBar -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'person-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'htmlOptions'=>array('style'=>'width:740px'),
	'pager'=>array(
		'header'=>'',
		'firstPageLabel'=>'&lt;&lt;',
		'prevPageLabel'=>'&lt;',
		'nextPageLabel'=>'&gt;',
		'lastPageLabel'=>'&gt;&gt;',
	),
	'columns'=>array(
		/*
		'id',
		'email:email',
		'webpage:url',
		'registered',
		*/
		array(
			'name'=>'lastname',
			'type'=>'raw',
			'value'=>'CHtml::link($data->lastname, $this->grid->controller->createReturnableUrl("view",array("id"=>$data->id)))',
		),
		'firstname',
		'birthyear',
		array(
			'name'=>'country_id',
			'value'=>'$data->country->name',
			'filter'=>Country::model()->options,
		),
		array(
			'name'=>'eyecolor_code',
			'value'=>'Lookup::item("eyecolor",$data->eyecolor_code)',
			'filter'=>Lookup::items('eyecolor'),
		),
		array(
			'class'=>'CLinkColumn',
			'header'=>Yii::t('ui','Email'),
			'imageUrl'=>XHtml::imageUrl('email.png'),
			'labelExpression'=>'$data->email',
			'urlExpression'=>'"mailto://".$data->email',
			'htmlOptions'=>array('style'=>'text-align:center'),
		),
		array(
			'class'=>'CButtonColumn',
			'viewButtonUrl'=>'$this->grid->controller->createReturnableUrl("view",array("id"=>$data->id))',
			'updateButtonUrl'=>'$this->grid->controller->createReturnableUrl("update",array("id"=>$data->id))',
			'deleteButtonUrl'=>'$this->grid->controller->createReturnableUrl("delete",array("id"=>$data->id))',
			'deleteConfirmation'=>Yii::t('ui','Are you sure to delete this item?'),
		),
	),
)); ?>

<br />

<div class="tpanel">
<div class="toggle"><?php echo Yii::t('ui','View code'); ?></div>
<?php $this->beginWidget('CTextHighlighter',array('language'=>'PHP')); ?>
$this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'person-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'pager'=>array(
		'header'=>'',
		'firstPageLabel'=>'&lt;&lt;',
		'prevPageLabel'=>'&lt;',
		'nextPageLabel'=>'&gt;',
		'lastPageLabel'=>'&gt;&gt;',
	),
	'columns'=>array(
		array(
			'name'=>'lastname',
			'type'=>'raw',
			'value'=>'CHtml::link($data->lastname,
				$this->grid->controller->createReturnableUrl("view",array("id"=>$data->id)))',
		),
		'firstname',
		'birthyear',
		array(
			'name'=>'country_id',
			'value'=>'$data->country->name',
			'filter'=>Country::model()->options,
		),
		array(
			'name'=>'eyecolor_code',
			'value'=>'Lookup::item("eyecolor",$data->eyecolor_code)',
			'filter'=>Lookup::items('eyecolor'),
		),
		array(
			'class'=>'CLinkColumn',
			'header'=>Yii::t('ui','Email'),
			'imageUrl'=>XHtml::imageUrl('email.png'),
			'labelExpression'=>'$data->email',
			'urlExpression'=>'"mailto://".$data->email',
			'htmlOptions'=>array('style'=>'text-align:center'),
		),
		array(
			'class'=>'CButtonColumn',
			'viewButtonUrl'=>'$this->grid->controller->createReturnableUrl("view",array("id"=>$data->id))',
			'updateButtonUrl'=>'$this->grid->controller->createReturnableUrl("update",array("id"=>$data->id))',
			'deleteButtonUrl'=>'$this->grid->controller->createReturnableUrl("delete",array("id"=>$data->id))',
			'deleteConfirmation'=>Yii::t('ui','Are you sure to delete this item?'),
		),
	),
));
<?php $this->endWidget(); ?>
</div>

<div class="tpanel">
<div class="toggle"><?php echo Yii::t('ui','Browse code'); ?></div>
<pre>
protected/controllers/PersonController.php: public function actionAdmin()
protected/models/Person.php
</pre></div>

protected/views/person/alpha.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Yii::t('ui', 'Alpha pagination');
$this->leftPortlets=null;
$this->leftPortlets['ptl.ExtensionMenu']=array();
?>

<h2><?php echo Yii::t('ui', 'Alpha pagination'); ?></h2>

<?php $this->widget('ext.widgets.alphapager.XAlphaLinkPager',array(
	'pages'=>$alphaPages,
	'header'=>false,
)); ?>

<br /><br />

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'ajaxUpdate'=>false,
	'template'=>'{pager}{sorter}{summary}{items}{pager}',
	'itemView'=>'_view',
	'pager'=>array(
		'header'=>false,
		'maxButtonCount'=>'9',
	),
	'sortableAttributes'=>array(
		'firstname',
		'lastname',
		'birthyear',
	),
)); ?>

<div class="tpanel">
<div class="toggle"><?php echo Yii::t('ui','View code'); ?></div>
<?php $this->beginWidget('CTextHighlighter',array('language'=>'PHP')); ?>
$this->widget('ext.widgets.alphapager.XAlphaLinkPager',array(
	'pages'=>$alphaPages,
	'header'=>false,
));

$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'ajaxUpdate'=>false,
	'template'=>'{pager}{sorter}{summary}{items}{pager}',
	'itemView'=>'_view',
	'pager'=>array(
		'header'=>false,
		'maxButtonCount'=>'9',
	),
	'sortableAttributes'=>array(
		'firstname',
		'lastname',
		'birthyear',
	),
));
<?php $this->endWidget(); ?>
</div>

<div class="tpanel">
<div class="toggle"><?php echo Yii::t('ui','Browse code'); ?></div>
<pre>
protected/controllers/PersonController.php: public function actionAlpha()
protected/models/Person.php
protected/views/person/_view.php
</pre></div>

protected/views/person/create.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Yii::t('ui', 'New Person');

$this->breadcrumbs=array(
	Yii::t('ui','Persons')=>array('admin'),
	Yii::t('ui','New'),
);
?>

<h2><?php echo Yii::t('ui', 'New Person'); ?></h2>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/person/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Yii::t('ui', 'Persons');

$this->breadcrumbs=array(
	Yii::t('ui','Persons'),
);
?>

<h2><?php echo Yii::t('ui', 'Persons'); ?></h2>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'ajaxUpdate'=>false,
	'template'=>'{sorter}{pager}{summary}{items}{pager}',
	'itemView'=>'_view',
	'pager'=>array(
		'maxButtonCount'=>'7',
	),
	'sortableAttributes'=>array(
		'firstname',
		'lastname',
		'birthyear',
	),
)); ?>

<br />

<div class="tpanel">
<div class="toggle"><?php echo Yii::t('ui','View code'); ?></div>
<?php $this->beginWidget('CTextHighlighter',array('language'=>'PHP')); ?>
$this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'ajaxUpdate'=>false,
	'template'=>'{sorter}{pager}{summary}{items}{pager}',
	'itemView'=>'_view',
	'pager'=>array(
		'maxButtonCount'=>'7',
	),
	'sortableAttributes'=>array(
		'firstname',
		'lastname',
		'birthyear'
	),
));
<?php $this->endWidget(); ?>
</div>

<div class="tpanel">
<div class="toggle"><?php echo Yii::t('ui','Browse code'); ?></div>
<pre>
protected/controllers/PersonController.php: public function actionIndex()
protected/models/Person.php
protected/views/person/_view.php
</pre></div>

protected/views/person/update.php
<?php
$this->pageTitle=Yii::app()->name . ' - ' . Yii::t('ui', 'Update Person');

$this->breadcrumbs=array(
	Yii::t('ui','Persons')=>$this->getReturnUrl() ? $this->getReturnUrl() : array('index'),
	Yii::t('ui','Update'),
);
?>

<h2><?php echo Yii::t('ui', 'Update Person'); ?></h2>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>